### ISSUE TITLE
GAME_STATE enum needs to be public.  The UserInterface can't do anything with it right now because it can't see it.

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#10]

**Comment by jtara1** [comment]
I'm working on updating the `UserInterface` class I've been working on. I got a solution to what we were talking about yesterday with handling a `USER_COMMAND` or `DIRECTION` (for player move).

The code runs right now on the latest commit, but it has some bugs, I'll fix shortly.

**Comment by Jester565** [comment]
Ok, this is a GameEngine problem so this is technically Francisco's issue
to fix. But because its necessary that this works for you right now, go
ahead and fix it.

**Comment by jtara1** [comment]
@frfabianrp Also, the variable `gameStatus` should probably be assigned to the value `GAME_STATE.UNFINISHED` in the `reset()` method of `GameEngine` in case we implement a next level feature later on.

**Comment by frfabianrp** [comment]
Ok, just committed changed

**Comment by frfabianrp** [comment]
Changes*
