### ISSUE TITLE
playerShoot(DIRECTION) method in GameEngine needs improvement

### ISSUE THREAD

**Issue by jtara1** [Jester565/SpyNinjaGame#11]
I haven't looked at the method lately, but it seems it prints out a negative coord in the debug prints, and returns true even though there was nothing for the bullet to hit. See photos:

Just shot:
![screenshot_20161116_113329](https://cloud.githubusercontent.com/assets/7478231/20362573/f6e9a446-abf0-11e6-9f67-bcbad1c43c3e.png)

then entered debug mode:
![screenshot_20161116_113401](https://cloud.githubusercontent.com/assets/7478231/20362590/041fd61c-abf1-11e6-8683-7110724070af.png)

**Comment by Jester565** [comment]
I agree.  Jessica is working on this, but I am going to put up a separate
branch with my own implementation in shooting.  If anyone needs any help
with shooting refer to it.  Should be up in about 2 hours.

**Comment by Jester565** [comment]
Here is a link to a commit where I have fully functional shooting.  Use
this as an example DO NOT MERGE DevAhead branch with master.

**Comment by jrcastron** [comment]
ya i think i had it say when it hits the edge of the board or a room

**Comment by Jester565** [comment]
Here are some possible issues with the current shooting mechanism
1. There is a new instance of Grid in Gun.
2. There is a new instance of Gun in GameEngine (get rid of this) and using it in your GameEngine.playerShoot call.  Maybe you should be calling spy.shoot(...) instead.
3. Weapon.attack() is unused in Gun (you're going to have to take another look at Weapon)
4. Ammo is not being reduced when shooting
5. The amount of ammo is not checked before shooting
6. There needs to be an ammo limit.  See this commit for a implementation of addBullets: 9d3957731db03d96f45a7f2b83dec208acf7d179
7. There is no need for the hit and collision booleans to be fields of the Gun class.  They should be variables declared within the method shoot (see 8 for how to check if shot was succesfull)
8. Make shoot return a boolean indicating if a shot was a hit or not.  We don't really need to know if it collided with a room.
9. If you think about it, sword and gun do the same thing but at different ranges... Perhaps there are some common attributes and behaviors you can come up with (3948ffc97eeaf3193f280322659b70b4f82f22f3).

Warning: The only reason GameEngine.rooms is being created is for the shoot method.  If you change your implementation to not use this ArrayList, make sure you get rid of it.

I have a working implementation in this commit as an example but yours is pretty close to working: 3948ffc97eeaf3193f280322659b70b4f82f22f3

**Comment by jrcastron** [comment]
thats super helpfull thx :3

**Comment by jtara1** [comment]
There's some smaller changes that are needed in the `Gun` class.
- `numRounds` is never initialized to any value so assign that variable a value in the constructor
- there's two fields in `Gun` that need visibility modifiers

**Comment by jtara1** [comment]
It seems this issue could be closed as the shoot feature works as expected. Relevant commits: 68855c00a5effbf8e5a5eec6b62847a5e72ea37a 28bb4b3e53b5f14e381ad4eb0a7fb49555dd2563 

Ninjas still don't die if they're shot so we could open a new issue to deal with that.

**Comment by jtara1** [comment]
Closing this issue, I think we sorted it out with the frenzy of commits today (11/21/16).

**Comment by Jester565** [comment]
Amen
