### ISSUE TITLE
The briefcase needs to be shown when we entered debug mode

### ISSUE THREAD

**Issue by jtara1** [Jester565/SpyNinjaGame#12]
In the photo I enter debug mode, but all the rooms still get printed as the letter `R`

Yesterday I added a method to `Room` called `revealBriefCase()`. This'll change the `gridRepresentation` from `R` to `b` if `hasBriefcase` is true. We can use this to help us reveal the briefCase.

![screenshot_20161116_114502](https://cloud.githubusercontent.com/assets/7478231/20362969/47ea9d18-abf2-11e6-8fa7-e865c95bcc04.png)

Right now I'm not sure if this would be done in GameEngine or UserInterface so I'll assign @frfabianrp and myself.

**Comment by Jester565** [comment]
I think this is best handled in the Room.  Perhaps you could override
GameObject's getGridRepresentation method in the Room class so that if
GameEngine.DebugMode is true and Room hasBriefCase(), it will return a b
instead of R.

**Comment by jtara1** [comment]
That works nicely. Now we shouldn't need an external reference to any Room in GameEngine unless there was another reason.
Closing with commit 70ab59457f56e81b00e3199235d773b98ecf6e94

**Comment by Jester565** [comment]
We will actually need an external reference to the briefcase room so the
radar power up can call that reveal briefcase method.  Jason should handle
this.

**Comment by Jester565** [comment]
Sorry thought it was showing it in non debug mode but it's good.

**Comment by Jester565** [comment]
Put the reveal briefcase method back in and make sure it is working.  We
need it for the radar.

**Comment by jtara1** [comment]
Done with commit 7e7832c2e8cff4c43f368e67d56ad8cf5ea50623
