### ISSUE TITLE
How do we handle maximum ammo and the Bullet power up.

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#13]
The maximum and initial amount of ammo in the Gun is 1.  The professor states this about the Bullet power up: _If the player hasn't used his initial bullet, the power-up will have no effect._

So the Spy picks up the Bullet power up and still has his initial round.  Which behavior do we want?
1. The Bullet power up is consumed (set to null) and has no effect on the Spy's ammo.
2. The Bullet power up is not consumed and can be picked up at a later time.

**Comment by jtara1** [comment]
I think option 2 makes more sense. 

Does option 1 mean the Spy would throw the bullet off the grid just because he doesn't need it at the moment? /s

I guess it's important to make sure you follow the rules the professor provided precisely though. Maybe we should ask him about this?

**Comment by Jester565** [comment]
In option 1 the power up would be set to null (so yeah its removed from the
grid).  Option 2 the power up won't be used and removed until it is needed.

**Comment by Jester565** [comment]
I say option 2 makes the most sense too and have implemented it in the DevAhead branch.  However, I'm not going to close this until it is implemented in the master branch.

**Comment by jtara1** [comment]
Closing with commit bfbf8fe6480d725bcecca5ca6d40b263cee447d8 though there's a few small changes to be done in issue #24
