### ISSUE TITLE
After getting killed by a Ninja, should we show where he was?

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#14]
In DevAhead, if you get killed by a Ninja right now it just prints out a message saying you lost.  This can suck because if you got killed by a Ninja you kind of want to know where he got you from.  Therefore, I think printing out a Grid showing the killer Ninja after dying would be a good idea.  Do you agree or is this a bad idea?

**Comment by jtara1** [comment]
I think it would be a really good idea to do this because it's very likely a ninja kills spy from the darkness.

Maybe when spy dies we enable debug mode, print the board, then print the message "You died to a ninja (check the board for the final state of the game)"

**Comment by jtara1** [comment]
When the `GAME_STATE.LOST` game state is reached (in `UserInterface.gameLoop()`) we enable `DebugMode` and print out the grid.

This allows the player to see where the `spy` and adjacent `ninja` were last (along with everything else).

Closing with commit 41fd5f876bc850bb0e6badf30e5dda5596ec40cb
