### ISSUE TITLE
When do Ninjas try to kill?

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#15]
The professor states "Ninjas will start every turn by checking if the spy is at an adjacent square. If the player is at an adjacent square, the ninja will 'mortally stab' him, killing the spy. Otherwise, the ninja will move one square in a random direction."

This makes me think that the steps are (Option A)
1. Check if the Spy is in range and kill him if he is
2. Move the Ninjas

Rather than the proposed (Option B)
1. Check if the spy is in range and kill him if he is
2. Move the Ninjas
3. Check if the spy is in range and kill him if he is

Which one is correct Option A or Option B?

**Comment by jtara1** [comment]
I interpret the professor's instructors as describing option A you have here.

**Comment by Jester565** [comment]
Yeah let's go with option A.  You can see that implemented in this commit: 8fe8ab20becf0d4eef1e7343ffb1fa2a40f431aa .  However, I'm going to assign Francisco to implement this into the master branch.

**Comment by jtara1** [comment]
Closing this issue with commit 27c3d4877bc6811d7ceeb0c4c9c24ad968de2102

**Comment by jtara1** [comment]
Just realized the ninja attacking hasn't been implemented yet.

**Comment by jtara1** [comment]
Closing with commit b6c341670946165c81daf01bd007e5fcbf7270c6, n1
