### ISSUE TITLE
When a Spy makes an Illegal move, do they get another chance to move?

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#17]
If a Spy walked onto the wrong side of a room or tried to walk out of bounds does he get another chance?

**Comment by Jester565** [comment]
The professor answered that the player should get another chance.  I then asked him, "If a player steps onto a Ninja, would that kill the player or would the player get another chance to move?"
Professor: "The player would get another chance to move"

If anyone is confused on that last part, tell me.  He was confused with what I was talking about too.

**Comment by Jester565** [comment]
Oh yeah.  Fixing this is mostly a UserInterface issue.  However, we are going to have to make another MOVE_RESULT for checking a room with an empty briefcase in it.  Right now, we just say MOVE_RESULT.ILLEGAL when there is no briefcase but that would give the player another chance to move.  So maybe something like MOVE_RESULT.UNMOVED would indicate that the player should not be moved, but the turn should end.

**Comment by jtara1** [comment]
Sounds good. I'll make these changes later this evening when I get a chance.

**Comment by Jester565** [comment]
I fixed this in the DevAhead branch in this commit perhaps you'll find it useful: 9dc2bccbb8420d166e521e7a7d8d034b5964e056

**Comment by jtara1** [comment]
@Jester565 can you explain why it was decided `MoveStatus` would be a class instead of an enum. I see it contains an enum, `MOVE_RESULT`, but why create it like this?

edit: ok got it, was a bit confused by some syntax, I can work with this without having to refactor anything

**Comment by Jester565** [comment]
Sure.  There are two fields in MoveStatus, moveResult and msg.  The msg provides a unique description of the step and the only purpose of it is to be printed out by the UserInterface.  The moveResult is more for the program and helps process the move.  You could return a MOVE_RESULT but the user wouldn't get those unique messages.  If you don't think we need those messages then switch out MoveStatus with MOVE_RESULT.

**Comment by Jester565** [comment]
So many things just happened lol

**Comment by jtara1** [comment]
Don't worry, I've only begun to spam the inboxes of you 3 who are "watching" this repository lmao. The other 2 have already opted to **unwatch** to avoid the spam though it is still good to follow the team's progress on this project.

If anyone wants to do that that'd be ok since you'll still get email if someone "@ mentions you" (@jtara1) or if someone assigns you to an issue I believe.

**Comment by Jester565** [comment]
I like the spam
