### ISSUE TITLE
Ninjas can't occupy the space of an Item

### ISSUE THREAD

**Issue by frfabianrp** [Jester565/SpyNinjaGame#20]
Currently a Ninja checks all 4 directions before making a move:

- It can't move out of the Grid bounds

- It can't move into a Room

- It can't move on the space occupied by an Item

I think last time we talked about it and a Ninja is supposed to be able to "step" on an Item. I'm sure @jtara1 @Jester565 solved this already haha but I wanted to try submitting a new issue.

**Comment by jtara1** [comment]
In #16 we discussed if ninjas could spawn on a `Useable`. I think ninjas should be able to move onto a `Useable` no problem. I'm going to make a comment on the specific line in your commit in a sec.

**Comment by Jester565** [comment]
There is an issue that both of you guys are going to have to work on.  I'm going to post it in a couple of minutes.
