### ISSUE TITLE
game can't end when you are surround by ninjas in normal mode

### ISSUE THREAD

**Issue by enochhz** [Jester565/SpyNinjaGame#32]
<img width="475" alt="screen shot 2016-11-23 at 9 09 24 am" src="https://cloud.githubusercontent.com/assets/17519068/20571601/fb0413d8-b15c-11e6-9ccc-1e5c30f5b666.png">
<img width="440" alt="screen shot 2016-11-23 at 9 09 40 am" src="https://cloud.githubusercontent.com/assets/17519068/20571606/fc30bdba-b15c-11e6-9e2e-a338799a0226.png">
<img width="438" alt="screen shot 2016-11-23 at 9 09 55 am" src="https://cloud.githubusercontent.com/assets/17519068/20571608/fd55a57a-b15c-11e6-8b85-36804bb74e52.png">

**Comment by enochhz** [comment]
it works fine in debug mode
<img width="509" alt="screen shot 2016-11-23 at 9 16 08 am" src="https://cloud.githubusercontent.com/assets/17519068/20571719/82e4cb9e-b15d-11e6-92f9-19e5b5909ff4.png">

**Comment by jtara1** [comment]
Commit 26639c472cdf2a0a5202c1a7fa765d6cd9ce6552 should fix this.

Here's my game prints showing it's working.

```
Move Status: Moved!
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Lives: 3
[ ][R][ ][ ][R][ ][ ][R][ ]   Ammo: 1
[ ][ ][ ][ ][ ][ ][N][ ][ ]   Invincible Turns: 0
[ ][ ][ ][N][ ][ ][ ][ ][ ]   Radar: Disabled
[ ][R][ ][ ][R][ ][B][R][ ]
[N][ ][ ][ ][ ][ ][ ][ ][I]
[ ][ ][ ][ ][ ][ ][ ][ ][ ]
[N][R][ ][ ][R][ ][ ][b][ ]
[N][S][N][ ][ ][ ][ ][ ][ ]

You cannot move... enter s to stand still or another command
1: Shoot | 2: Debug | 3: More Options | 4: HardMode
2
DebugMode: false
[*][*][*][*][*][*][*][*][*]   Lives: 3
[*][R][*][*][R][*][*][R][*]   Ammo: 1
[*][*][*][*][*][*][*][*][*]   Invincible Turns: 0
[*][*][*][*][*][*][*][*][*]   Radar: Disabled
[*][R][*][*][R][*][*][R][*]
[*][*][*][*][*][*][*][*][*]
[*][*][*][*][*][*][*][*][*]
[*][R][*][*][R][*][*][R][*]
[*][S][*][*][*][*][*][*][*]

You cannot move... enter s to stand still or another command
1: Shoot | 2: Debug | 3: More Options | 4: HardMode
s
Stood still
[*][*][*][*][*][*][*][*][*]   Lives: 2
[*][R][*][*][R][*][*][R][*]   Ammo: 1
[*][*][*][*][*][*][*][*][*]   Invincible Turns: 0
[*][*][*][*][*][*][*][*][*]   Radar: Disabled
[*][R][*][*][R][*][*][R][*]
[*][*][*][*][*][*][*][*][*]
[*][*][*][*][*][*][*][*][*]
[*][R][*][*][R][*][*][R][*]
[*][S][N][*][*][*][*][*][*]

You were stabbed by the ninja, press enter to continue
```
