### ISSUE TITLE
Game finish situation bug!

### ISSUE THREAD

**Issue by enochhz** [Jester565/SpyNinjaGame#36]
# Situation 1: Game Over 3 times, and spy keep losing lives
<img width="396" alt="screen shot 2016-11-23 at 11 42 00 am" src="https://cloud.githubusercontent.com/assets/17519068/20576802/4bcdb85c-b174-11e6-940c-f6f854045ca6.png">

# Situation 2: Game Win three times

<img width="397" alt="screen shot 2016-11-23 at 11 38 37 am" src="https://cloud.githubusercontent.com/assets/17519068/20576827/6312c34a-b174-11e6-81ab-9bdc73bbb410.png">

**Comment by jtara1** [comment]
What might be causing this is that I'm using recursive calls at certain points. I'll refactor the code to not do this while still preventing toggling debug or hard mode from ending the player turn.

**Comment by jtara1** [comment]
Commit 4cbf9dd370d49cb60648311faa2e8af8966b14f9 may solve this, not sure.

Does this consistently happen or only under certain conditons?
