### ISSUE TITLE
Gun needs to hold 2 bullets

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#38]
@jrcastron We need Gun's max ammo to be 2.

**Comment by jrcastron** [comment]
done :3

**Comment by jtara1** [comment]
Quote from Professor's assignment sheet
>Additional Bullet: like the name says, it will grant the player an additional bullet. If the player hasn't used his initial bullet, the power-up will have no effect.

This contradicts what he said in class today.

---

As for commit dbe7bdd8fe463565533047be37f5048f8e8cb620

Just changing `MAX_ROUNDS` to `2` also changed the initial amount of bullets the Spy has. Pretty sure Spy is supposed to start with 1 bullet.

**Comment by Jester565** [comment]
I'll email him asking.

**Comment by jrcastron** [comment]
ill wait to change anything else till he replys

**Comment by Jester565** [comment]
I never got a response but we won't get marked down for following the instructions on Blackboard
