### ISSUE TITLE
GUI Mode Issues

### ISSUE THREAD

**Issue by YaysonKwok** [Jester565/SpyNinjaGame#39]
@Jester565 
1. Upon winning a new game and being sent back to the main menu, the player still has control and can move around opening doors or getting killed.

2. Full screen doesn't work for me. Windows 10 OS and 1920x1080 Resolution
Upon hitting 'f', this is what displays for me on the main menu.
![image](https://cloud.githubusercontent.com/assets/22648263/20769505/0763c638-b6f7-11e6-81ca-c5a12e298c31.png)
In-game looks like this.
![image](https://cloud.githubusercontent.com/assets/22648263/20769536/28f307d2-b6f7-11e6-962c-e6f2629b3362.png)

**Comment by Jester565** [comment]
Are you running this on Windows 10?

**Comment by Jester565** [comment]
I couldn't replicate either of the issues.  I've attempted to fix them but I can't do anything except guess whats wrong without the computer.  Were the images back when you switched to window mode?

**Comment by Jester565** [comment]
From what I can tell, your computer is failing to load all images.  Are you getting any errors in the console?

**Comment by YaysonKwok** [comment]
Console remains empty and returning back to windowed mode left the GUI the same

**Comment by Jester565** [comment]
By left the GUI the same.  You mean there were no images.

**Comment by Jester565** [comment]
Is anyone else having this problem?

**Comment by Jester565** [comment]
Attempted to fix the issue with commit 8ecf38fdcbf0f56f92e12da674911f5fd03238d6 .  Can you try running it again?

**Comment by YaysonKwok** [comment]
Different issue now when fullscreening. Exception Error.
Testing out new game now.
Edit - New game. No movement on main menu works for me now

```
Exception in thread "main" java.lang.IllegalStateException: Buffers have not been created
	at sun.awt.windows.WComponentPeer.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.flip(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.show(Unknown Source)
	at jgraphic.DisplayManager.update(DisplayManager.java:104)
	at jgraphic.Core.run(Core.java:29)
	at edu.cpp.cs.cs141.final_proj.Main.main(Main.java:25)
```

**Comment by Jester565** [comment]
Your computer seems to be having a hard time creating a buffer strategy...
I'll see what I can do

**Comment by Jester565** [comment]
Alright I made a second attempt.  See if this works.

**Comment by YaysonKwok** [comment]
Works perfectly now in both main menu and in-game.

**Comment by Jester565** [comment]
Woah!  Can't believe that worked...  Thanks for reporting it.  Keep those bugs coming!  Also, the Mac should have a black background now.

**Comment by jtara1** [comment]
Running this on craptop with Windows 10:

I'm getting 60-70 fps in most cases, 30+ fps on death animation.

---

Minor bug:

While debug mode is enabled during death animation I could see the alien in the adjacent room in the cut scene with the alien killing the space explorer.

**Comment by Jester565** [comment]
Its not worth fixing the aliens showing in another room.  You're in Debug mode so your going to see things that aren't intended to be seen.

**Comment by Jester565** [comment]
@jtara1 Can you test the GUI on Ubuntu?

**Comment by Jester565** [comment]
GUI testing on Ubuntu is now being done in issue #40
