### ISSUE TITLE
GUI Testing on Mac

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#41]
Full screen mode and background should be tested in OSX

**Comment by enochhz** [comment]
# Full screen mode works well, but the background is still white

<img width="1440" alt="screen shot 2016-11-30 at 8 29 30 pm" src="https://cloud.githubusercontent.com/assets/17519068/20781948/332888ea-b73c-11e6-9d39-2dd1052d764d.png">

**Comment by Jester565** [comment]
Well that is the opposite of what I expected.  I thought it would be black but fullscreen wouldn't work.  I made a commit that should fix it. Pull, refresh, and try again.

**Comment by enochhz** [comment]
after pulling, the background is still white

**Comment by Jester565** [comment]
Did you refresh?

**Comment by Jester565** [comment]
If it's still white I'm never going to buy a mac.

**Comment by enochhz** [comment]
yes, i refreshed

**Comment by enochhz** [comment]
:(

**Comment by Jester565** [comment]
Wait my changes didn't commit for some reason.  Pull, refresh, and try again.

**Comment by enochhz** [comment]
yeah,finally

<img width="1440" alt="screen shot 2016-11-30 at 8 51 13 pm" src="https://cloud.githubusercontent.com/assets/17519068/20782232/cc8b5a88-b73e-11e6-9ebb-0f98bb6b6d83.png">

**Comment by Jester565** [comment]
Alright, I guess I can still buy a mac.

**Comment by enochhz** [comment]
haha
