### ISSUE TITLE
Instructions will be added

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#42]
This is a warning... Wait to test the GUI for a bit.  I am improving the instructions for the game.  Since our project is going to be used as an example for next quarter (which is freaking awesome), I'm going to add descriptions for objects and stuff.

**Comment by jtara1** [comment]
Used for the next quarter? Probably used for eternity. It'd take some madmen to out-due this within 3 weeks especially coming from a CS141 class. Btw we should try publishing this on steam.

**Comment by Jester565** [comment]
Your right I'm gonna go green light this.
