### ISSUE TITLE
Can the spy see the tile on the other side of the door?

### ISSUE THREAD

**Issue by jtara1** [Jester565/SpyNinjaGame#5]
Should the scenario in this image be allowed?

![screenshot_20161114_235003](https://cloud.githubusercontent.com/assets/7478231/20297407/3f20005c-aac5-11e6-9548-88ae40610376.png)

This issue is a very low priority issue right now.

**Comment by Jester565** [comment]
I don't know...  We will have to ask the professor tomorrow

**Comment by jtara1** [comment]
Fix with commit aa5643ec779e432e710b04a160d5528e745f5089
