### ISSUE TITLE
Scanner method nextInt() leaves behind newline character that the next call to nextLine() picks up

### ISSUE THREAD

**Issue by jtara1** [Jester565/SpyNinjaGame#6]
This was causing this "Invalid ... " statement to be printed when nothing had been typed yet.

![screenshot_20161115_001514](https://cloud.githubusercontent.com/assets/7478231/20298149/18ee8300-aac9-11e6-89e0-22d9b39d4d53.png)

**Comment by Jester565** [comment]
Just add another nextLine() after the main menu.

**Comment by Jester565** [comment]
Fixed issue in last commit.

**Comment by jtara1** [comment]
oh, was going to fix, should've assigned to myself

edit: going to sleep

edit2: fixed with commit ec5a9dba7df8124178be266e61d1d99fa1af199b

**Comment by Jester565** [comment]
That's alright... Teamwork!

**Comment by Jester565** [comment]
Commit fixed in: ec5a9dba7df8124178be266e61d1d99fa1af199b
