### ISSUE TITLE
There's two copies of the game in this repository

### ISSUE THREAD

**Issue by jtara1** [Jester565/SpyNinjaGame#9]
@walkerzheng I think you added other files in commit 37a324d930bacd203e684873c07396147eb28905. I don't think you made any commits for the new copies there.

Could you git remove it?

I'm pretty sure you said you were using git via terminal so

Change directory to the local project files of this repository then do
```
git rm SuperSpyGame\ copy/*

git commit -a -m "rm copy of game"

git push origin master
```

edit: closing with commit 706a96215a7aba4e0839d95414535312262ff56d

**Comment by Jester565** [comment]
Yeah that game should be in a separate repository.

**Comment by enochhz** [comment]
Yeah, I am deleting it
